version: '3.9'

services:
  mysql-db:
    image: mysql:8
    restart: always
    env_file:
    - ../configs/config.env
    ports:
    - "3307:3306"
    volumes:
    - ../migrations/001_migration.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
    - ofl_network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9999:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
    - ofl_network

networks:
  ofl_network:
    driver: bridge
