version: '3.9'

services:
  mysql-db:
    image: mysql:8
    restart: always
    env_file:
    - ../configs/config.env
    ports:
    - "3307:3306"
    volumes:
    - ../migrations/001_migration.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
    - ofl_network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9999:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
    - ofl_network
  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    networks:
    - ofl_network
  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    restart: always
    env_file:
    - ../configs/config_sheduler.env
    depends_on:
     zookeeper:
        condition: service_started
    expose:
    - "9092"
    networks:
    - ofl_network 

networks:
  ofl_network:
    driver: bridge
